apiVersion: v1
kind: Namespace
metadata:
  name: test-inventory-svc-git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: inventory-management-svc-2
  namespace: test-inventory-svc-git
  labels:
    name: inventory-management-svc-2
    app: inventory-management-svc-2
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
    - group: core
      kind: Pods
    - group: apps
      kind: Deployment
    - group: route.openshift.io
      kind: Route
    - group: core
      kind: Service
  descriptor: {}
  selector:
    matchLabels:
      app: inventory-management-svc-2
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: inventory-management-svc-2-rule
  namespace: test-inventory-svc-git
  generation: 1
  labels:
    purpose: inventory-management-svc-2
spec:
  clusterReplicas: 3
  clusterLabels:
    matchLabels:
      name: ibmcloud-sydney

---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: inventory-management-svc-2-ui
  namespace: test-inventory-svc-git
  generation: 1
  labels:
    app: inventory-management-svc-2
spec:
  name: inventory-management-ui
  channel: test-inventory-svc-git/helm-repo-testdrive-artifactory
  packageFilter:
    version: 0.0.5
  placement:
    placementRef:
      name: inventory-management-svc-2-rule
      kind: PlacementRule
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: inventory-management-svc-2-bff
  namespace: test-inventory-svc-git
  generation: 1
  labels:
    app: inventory-management-svc-2
spec:
  name: inventory-management-bff
  channel: test-inventory-svc-git/helm-repo-testdrive-artifactory
  packageFilter:
    version: 0.0.3
  placement:
    placementRef:
      name: inventory-management-svc-2-rule
      kind: PlacementRule
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: inventory-management-svc-2-svc
  namespace: test-inventory-svc-git
  generation: 1
  labels:
    app: inventory-management-svc-2
spec:
  name: inventory-svc
  channel: test-inventory-svc-git/helm-repo-testdrive-artifactory
  packageFilter:
    version: 0.0.2
  placement:
    placementRef:
      name: inventory-management-svc-2-rule
      kind: PlacementRule
---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: helm-repo-testdrive-artifactory
  namespace: test-inventory-svc-git
spec:
  configMap:
    insecureSkipVerify: true
  pathname: >-
    https://artifactory-tools.rhos4cpdv3anz-syd01-b3c-49940c4bdca5e22e4c30fc45d6b9da1b-0000.au-syd.containers.appdomain.cloud/artifactory/generic-local/testdrive
  type: HelmRepo
